build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.19
  amd64: ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.19
  armhf: ghcr.io/home-assistant/armhf-base-python:3.12-alpine3.19
  armv7: ghcr.io/home-assistant/armv7-base-python:3.12-alpine3.19
  i386: ghcr.io/home-assistant/i386-base-python:3.12-alpine3.19
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Rako MQTT Bridge"
  org.opencontainers.image.description: "Bridge between Rako lighting system and MQTT"
  org.opencontainers.image.source: "https://github.com/errrrata/rakomqtt"
  org.opencontainers.image.licenses: "MIT"
