name: "Rako MQTT Bridge"
description: "Bridge between Rako lighting system and MQTT"
url: "https://github.com/errrrata/rakomqtt/tree/7-support-hassio-addon"
version: "0.2.16"
slug: "rako_mqtt_bridge"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
icon: "icon.svg"
startup: application
boot: auto
host_network: true
services:
  - mqtt:need
options:
  rako_bridge_host: ""
  mqtt: []
  debug: false
  default_fade_rate: "medium"
schema:
  rako_bridge_host: str?
  mqtt:
    - server: str?
      user: str?
      password: str?
  debug: bool
  default_fade_rate: list(instant|fast|medium|slow|very_slow|extra_slow)
