name: "Rako MQTT Bridge"
#image: ghcr.io/home-assistant/{arch}-base-python:3.12-alpine3.19
version: "0.2.29"
slug: "rako_mqtt_bridge"
description: "Bridge between Rako lighting system and MQTT"
url: "https://github.com/errrrata/rakomqtt#7-support-hassio-addon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
#hassio_api: true
#hassio_role: default
startup: application
services:
  - mqtt:want
#boot: auto
#apparmor: true
host_network: true
options:
  rako_bridge_host: ""
  debug: false
  default_fade_rate: "medium"
schema:
  rako_bridge_host: str?
  mqtt_host: str
  mqtt_user: str
  mqtt_password: password
  debug: bool
  default_fade_rate: list(instant|fast|medium|slow|very_slow|extra_slow)
defaults:
  mqtt_host: "!secret mqtt_host"
  mqtt_user: "!secret mqtt_user"
  mqtt_password: "!secret mqtt_password"
