services:
  rakomqtt_bridge:
    image: rakomqtt
    container_name: rakomqtt
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - MQTT_HOST=${MQTT_HOST:-localhost}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - RAKO_BRIDGE_HOST=${RAKO_BRIDGE_HOST:-""}
      - DEFAULT_FADE_RATE=${DEFAULT_FADE_RATE:-medium}
      - TZ=${TZ:-UTC}
    command:
      - "./start.sh"
      - "--debug"
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9761"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /etc/localtime:/etc/localtime:ro
